### ISSUE TITLE
ability to fire tag on swipe

### ISSUE THREAD

**Issue by ndis1** [urbn/URBNSwipeableController#6]
for analytics, we need to know when the cell is swiped. the existing notification kSwiperControllerCloseAllKey is private, and can be posted in a couple different cases. 

I think we should add two notifications in basementDidAppear and basementDidDisappear

**Comment by flippinjoe** [comment]
My thought would be to add 2 notifications on top of the closeAll notification.   

These notifications would be tied directly to the scrolling logic.

**Comment by flippinjoe** [comment]
Fixed by [Pull #7](https://github.com/urbn/URBNSwipeableController/pull/7)
